language: node_js

node_js:
  - 8

deploy:
  - provider: script
    script: "./bin/deploy.sh"
    on:
      branch: master

env:
  global:
    - secure: Ntv0x4o4BUztq2qQfmxHquv1WlQTHa9jx95DdJlld/kJ76eL00L9JqzoeJK6/TAjXTOABfVpDognSyFfeMsL0bT093Im6PHuXYUsLFI7pFSi6ikBllcTffAw2F7ajKa1uoBRs4uuJ3Kd0qUlYuywwDK6BalIjAHnU2MiwVNlsKy8A5Wy3ZpB+XkSTKtVU1AjHTmPMavdVkk3QRnee/0tJ75XD8iMRWcVc2Qk+8/AbrkEXvbnV85tVNrIeXGzGaU3UeYes0QN2WuAWcGF5Y36suEvN9crNu4uCej3BbbWjG9cc+rSHQKwiQAcIDn23Jmx5A5Ytf4WPWfkp3ZRd7J/vZcz0Wfau9a8JZ0LA6MNq4/9NsjhUbBiG+8h0H401IwBmIIHvHzYr8Lr0fXfuZiNFguvYFiLJqZcB+sr3LV97tu3Oxb3rdYGe0dwL/VsjMEKKh8dOIY6t/bkY++jgDOvs59P36Pe5GWYYBuFR0KzRWbRU36AClIvXUPey5C8F/K62cOcxHYBgSfocjhRyuL/4/cPkdTXxoCsLx5Uo9KA1AZLP4k44ywApNJyZCcQKwbWLkbIYOuOwZmqaCPuZB8BpdZLYjUSour/uVaxaeX2xx8g1zQx5YsT/e/7XlWxPO7WUicqVjkK7kxONZxDnDiaCeaWf3Mv+/YLdU+Mha3ZFRA=
    - secure: SxGIgFBtXlDitIxM/XrqLSU0wfPcLM324aefJGBSHwHD8QasxDfyA9FWHOGdNfutx/ebu2BRnAOXsEJNQLYMnxW2/ayrxlfTVHJ+AXm4efFuid2QXXtFheovTmSZSS8fTkie36D2fIloY6h2FYhSxm/7hXMmiEhdnJzae1x9jieEgIix6moTUM1isFUfVlV7UEXuN6bexpVHdQlQlte6krbCCKNnoJXrgJ527qjTmSrzzUdtV/ZW2bPQPyXm2VsB1ekewc7p4HK4il7Fx8VyubAmOKJ0CH+FXeadmf6Vp2qTNDjy8ahB8K6JJ+49m47T5+YfJeIV/THA9oIIL325y1+ReloR3wXpyX2pEc2AYvbnkP6zhp2xMqzsEXTFPsUVIu133GD9pB1tpyChljZsdOLnz08YWn4o4I6CEm2MzGcRtHVxvHo0SZbylQtkqXRl7Z1UJZ8QsRFl3zE3IFqaub8FXQ8geaDt8rTYaRUXNgOyPCboG6wZ+LAprQvE5jl73XInNMKMA/Xk/XPIcIzJfuMhtAxZEa8wy61XJWKHmWm/GLN9jUWcceg0odpTrnOMKbS09r355H7bESYeosc0jE7A/NCTZMKY0jtumzUnxMvRzSY5H5TtB1p2iyXNdC9kshxFXR9RS+e8guwHiZEnD08d3faZHWuWYhNy6cKpRYA=
