service: tiny-rebel-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  getDrinks:
    handler: handler.getDrinks
    events:
      - http:
          path: /{barLocation}/drinks
          method: get
