service: tiny-rebel-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1

package:
 include:
   - ../node_modules/**

functions:
  getDrinksForBarLocation:
    handler: handler.getDrinksForBarLocation
    events:
      - http:
          path: /{barLocation}/drinks
          method: get

  getDrinksForAllLocations:
    handler: handler.getDrinksForAllLocations
    events:
      - http:
          path: /drinks
          method: get
